#!/usr/bin/env bash
# Same as setup-env.ps1 for Linux / macOS users.
# Re-runnable, prompts only — nothing is sent anywhere.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
backend_env="$repo_root/.env"
web_env="$repo_root/web/.env.local"

read_existing() {
  local file="$1" key="$2"
  [ -f "$file" ] || { echo ""; return; }
  awk -F= -v k="$key" '$1==k {sub(/^[^=]+=/,""); print; exit}' "$file"
}

mask() {
  local v="$1"
  [ -z "${2:-}" ] && { echo "$v"; return; }
  local n=${#v}
  if [ "$n" -le 6 ]; then echo "***"; else echo "${v:0:4}…${v: -4}"; fi
}

ask() {
  local label="$1" default="$2" secret="${3:-}"
  local hint=""
  [ -n "$default" ] && hint=" [current: $(mask "$default" "$secret")]"
  local v
  read -r -p "  ${label}${hint}: " v
  [ -z "$v" ] && v="$default"
  printf "%s" "$v"
}

write_env() {
  local file="$1" header="$2"
  shift 2
  mkdir -p "$(dirname "$file")"
  : > "$file"
  echo "$header" >> "$file"
  for kv in "$@"; do
    echo "$kv" >> "$file"
  done
}

echo
echo "==> Futbool env setup"
echo "    Files: $backend_env"
echo "           $web_env"
echo

declare -A E
for k in SUPABASE_URL SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY SUPABASE_JWT_SECRET \
         DATABASE_URL ANTHROPIC_API_KEY STRIPE_SECRET_KEY STRIPE_WEBHOOK_SECRET \
         STRIPE_PUBLISHABLE_KEY SPORTMONKS_API_KEY THE_ODDS_API_KEY FOOTBALL_DATA_ORG_KEY \
         OPENAI_API_KEY ELEVENLABS_API_KEY ELEVENLABS_VOICE_JOHN ELEVENLABS_VOICE_CARLOS \
         ELEVENLABS_VOICE_HANS ELEVENLABS_VOICE_EMRE APP_ENV APP_BASE_URL WEB_BASE_URL \
         USE_MOCK_PROVIDERS CLAUDE_MODEL REDIS_URL; do
  E[$k]="$(read_existing "$backend_env" "$k")"
done

echo "Supabase (required)"
SUPABASE_URL="$(ask 'SUPABASE_URL'              "${E[SUPABASE_URL]}")"
SUPABASE_ANON_KEY="$(ask 'SUPABASE_ANON_KEY'    "${E[SUPABASE_ANON_KEY]}" 1)"
SUPABASE_SERVICE_ROLE_KEY="$(ask 'SUPABASE_SERVICE_ROLE_KEY' "${E[SUPABASE_SERVICE_ROLE_KEY]}" 1)"
SUPABASE_JWT_SECRET="$(ask 'SUPABASE_JWT_SECRET' "${E[SUPABASE_JWT_SECRET]}" 1)"
DATABASE_URL="$(ask 'DATABASE_URL (optional)'   "${E[DATABASE_URL]}")"

echo
echo "Optional providers (leave blank to skip)"
ANTHROPIC_API_KEY="$(ask 'ANTHROPIC_API_KEY'           "${E[ANTHROPIC_API_KEY]}" 1)"
STRIPE_SECRET_KEY="$(ask 'STRIPE_SECRET_KEY'           "${E[STRIPE_SECRET_KEY]}" 1)"
STRIPE_WEBHOOK_SECRET="$(ask 'STRIPE_WEBHOOK_SECRET'   "${E[STRIPE_WEBHOOK_SECRET]}" 1)"
STRIPE_PUBLISHABLE_KEY="$(ask 'STRIPE_PUBLISHABLE_KEY' "${E[STRIPE_PUBLISHABLE_KEY]}")"
SPORTMONKS_API_KEY="$(ask 'SPORTMONKS_API_KEY'         "${E[SPORTMONKS_API_KEY]}" 1)"
THE_ODDS_API_KEY="$(ask 'THE_ODDS_API_KEY'             "${E[THE_ODDS_API_KEY]}" 1)"
FOOTBALL_DATA_ORG_KEY="$(ask 'FOOTBALL_DATA_ORG_KEY'   "${E[FOOTBALL_DATA_ORG_KEY]}" 1)"
OPENAI_API_KEY="$(ask 'OPENAI_API_KEY (Whisper)'       "${E[OPENAI_API_KEY]}" 1)"
ELEVENLABS_API_KEY="$(ask 'ELEVENLABS_API_KEY'         "${E[ELEVENLABS_API_KEY]}" 1)"
ELEVENLABS_VOICE_JOHN="$(ask 'ELEVENLABS_VOICE_JOHN'   "${E[ELEVENLABS_VOICE_JOHN]}")"
ELEVENLABS_VOICE_CARLOS="$(ask 'ELEVENLABS_VOICE_CARLOS' "${E[ELEVENLABS_VOICE_CARLOS]}")"
ELEVENLABS_VOICE_HANS="$(ask 'ELEVENLABS_VOICE_HANS'   "${E[ELEVENLABS_VOICE_HANS]}")"
ELEVENLABS_VOICE_EMRE="$(ask 'ELEVENLABS_VOICE_EMRE'   "${E[ELEVENLABS_VOICE_EMRE]}")"

APP_ENV="${E[APP_ENV]:-development}"
APP_BASE_URL="${E[APP_BASE_URL]:-http://localhost:8000}"
WEB_BASE_URL="${E[WEB_BASE_URL]:-http://localhost:3000}"
USE_MOCK_PROVIDERS="${E[USE_MOCK_PROVIDERS]:-true}"
CLAUDE_MODEL="${E[CLAUDE_MODEL]:-claude-opus-4-7}"
REDIS_URL="${E[REDIS_URL]:-}"

write_env "$backend_env" "# Generated by scripts/setup-env.sh — never commit." \
  "APP_ENV=$APP_ENV" \
  "APP_BASE_URL=$APP_BASE_URL" \
  "WEB_BASE_URL=$WEB_BASE_URL" \
  "USE_MOCK_PROVIDERS=$USE_MOCK_PROVIDERS" \
  "CLAUDE_MODEL=$CLAUDE_MODEL" \
  "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" \
  "SUPABASE_URL=$SUPABASE_URL" \
  "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" \
  "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY" \
  "SUPABASE_JWT_SECRET=$SUPABASE_JWT_SECRET" \
  "DATABASE_URL=$DATABASE_URL" \
  "REDIS_URL=$REDIS_URL" \
  "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY" \
  "STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY" \
  "STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET" \
  "SPORTMONKS_API_KEY=$SPORTMONKS_API_KEY" \
  "THE_ODDS_API_KEY=$THE_ODDS_API_KEY" \
  "FOOTBALL_DATA_ORG_KEY=$FOOTBALL_DATA_ORG_KEY" \
  "OPENAI_API_KEY=$OPENAI_API_KEY" \
  "ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY" \
  "ELEVENLABS_VOICE_JOHN=$ELEVENLABS_VOICE_JOHN" \
  "ELEVENLABS_VOICE_CARLOS=$ELEVENLABS_VOICE_CARLOS" \
  "ELEVENLABS_VOICE_HANS=$ELEVENLABS_VOICE_HANS" \
  "ELEVENLABS_VOICE_EMRE=$ELEVENLABS_VOICE_EMRE"

write_env "$web_env" "# Generated by scripts/setup-env.sh — never commit." \
  "NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL" \
  "NEXT_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" \
  "NEXT_PUBLIC_API_BASE_URL=$APP_BASE_URL"

echo
echo "Wrote $backend_env"
echo "Wrote $web_env"
echo
echo "Next:"
echo "  uvicorn backend.main:app --reload --port 8000"
echo "  cd web && npm run dev"
